// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0I29dksSMGuzJa6iDKBJ1Ikn-YTCcTEs',
    appId: '1:97755944829:web:e29f50d399719084421e14',
    messagingSenderId: '97755944829',
    projectId: 'aaskfj-4cb00',
    authDomain: 'aaskfj-4cb00.firebaseapp.com',
    storageBucket: 'aaskfj-4cb00.appspot.com',
    measurementId: 'G-BV34S1QYCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJBpdD3iJ2Td3hmDvEtLXKFZyhl7vv53Y',
    appId: '1:97755944829:android:789bb23d049b345d421e14',
    messagingSenderId: '97755944829',
    projectId: 'aaskfj-4cb00',
    storageBucket: 'aaskfj-4cb00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL6MCvieP0kGWqHP2b8B5J_YUbTMrS2i4',
    appId: '1:97755944829:ios:c042fd0f214c56f8421e14',
    messagingSenderId: '97755944829',
    projectId: 'aaskfj-4cb00',
    storageBucket: 'aaskfj-4cb00.appspot.com',
    iosBundleId: 'com.example.teamplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL6MCvieP0kGWqHP2b8B5J_YUbTMrS2i4',
    appId: '1:97755944829:ios:804aba2e0df11310421e14',
    messagingSenderId: '97755944829',
    projectId: 'aaskfj-4cb00',
    storageBucket: 'aaskfj-4cb00.appspot.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0I29dksSMGuzJa6iDKBJ1Ikn-YTCcTEs',
    appId: '1:97755944829:web:1578a6a20cc94b69421e14',
    messagingSenderId: '97755944829',
    projectId: 'aaskfj-4cb00',
    authDomain: 'aaskfj-4cb00.firebaseapp.com',
    storageBucket: 'aaskfj-4cb00.appspot.com',
    measurementId: 'G-371GM4PNRN',
  );
}
